### PR TITLE
Add `with_parameter` and `without_parameters`

### PR DESCRIPTION
**Pull request by douglasdavis**

### CODE REVIEW

**Comment by douglasdavis** [comment]
I'm not quite sure how to test this off the top of my head; @jpivarski or @lgray any thoughts?

**Comment by lgray** [comment]
A good test would be to add and remove an empty dictionary, make sure it is there, make sure it is not there.

**Comment by lgray** [comment]
And yes, indeed, check the results after a compute! I'll also be needing to manipulate the parameters of the dak.Array as well. So both sides need to be appropriately persitent and correct.

**Comment by douglasdavis** [comment]
Alright I've added a test that adds and removes a trivial parameter, it makes sure that the collection metadata has the parameter, as well as the computed result.

**Pull request merged**
